#!/bin/bash

FILE=~/.tts
echo "tts-speak-listener"

if test -p "$FILE"; then
    echo "$FILE exist"
else
    echo "$FILE not found, creating it now:"
    echo "mkfifo $FILE"
    mkfifo ~/.tts
fi

echo "Press Control-C to stop listening"
while true; do cat ~/.tts; done | termux-tts-speak

