#!/bin/bash

FILE=~/.tts
echo "tts-speak-prompt"

if test -p "$FILE"; then
    echo "$FILE exist"
else
    echo "$FILE not found, creating it now:"
    echo "mkfifo $FILE"
    mkfifo ~/.tts
fi

while true;
do
    read MESSAGE
    echo $MESSAGE > $FILE
done


